### ISSUE TITLE
forwarding to haldean.org

### ISSUE THREAD

**Issue by umtksa** [haldean/docstore#2]
I forked your reposity but index.html forwards me to halden.org now showing my own content

**Comment by haldean** [comment]
You're going to need to edit these lines to point wherever you want them to point, instead of at my website.

Point this one at your github repository:
https://github.com/haldean/docstore/blob/95ac07d6fe71e171afe1daba5751db7f4f63c9be/js/docstore.js#L44

Point these at your domain name:
https://github.com/haldean/docstore/blob/95ac07d6fe71e171afe1daba5751db7f4f63c9be/index.html#L16
https://github.com/haldean/docstore/blob/95ac07d6fe71e171afe1daba5751db7f4f63c9be/index.html#L29
